# Generated by Django 3.2.2 on 2021-09-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='BLOG_TABLE',
        ),
    ]
